function [] = check_hydromech(step,xm,ym,tk0,tk1,tk2,DT,APHI,vxf,vyf,pscale,ETA,ETAP,GGG,...
    GGGP,SXY0,SXX0,RHOX,RHOY,RHOFX,RHOFY,RX,RY,ETAPHI,BETTAPHI,PHI,gx,gy,...
    pr0,pf0,dt,R,L_d,S,vx,vy,qxD,qyD,pr,pf)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
close all;
disp(['CHECKING HYDROMECH INPUTS/OUTPUTS timestep=' num2str(step)]);
[xm_jl,ym_jl,tk0_jl,tk1_jl,tk2_jl,DT_jl,APHI_jl,vxf_jl,vyf_jl,pscale_jl,ETA_jl,ETAP_jl,GGG_jl,...
    GGGP_jl,SXY0_jl,SXX0_jl,RHOX_jl,RHOY_jl,RHOFX_jl,RHOFY_jl,RX_jl,RY_jl,...
    ETAPHI_jl,BETTAPHI_jl,PHI_jl,gx_jl,gy_jl,pr0_jl,pf0_jl,dt_jl,R_jl,...
    L_jl,S_jl,vx_jl,vy_jl,qxD_jl,qyD_jl,pr_jl,pf_jl] = M_1078(step);
disp(['xm' '------------------------------------------']);
[~,~,f]=check(xm,xm_jl);
saveas(f, ['abs error xm step=' num2str(step) '.png']);
disp(['ym' '------------------------------------------']);
[~,~,f]=check(ym,ym_jl);
saveas(f, ['abs error ym step=' num2str(step) '.png']);
disp(['tk0' '------------------------------------------']);
[~,hm,f]=check(tk0,tk0_jl);
hm.Title = ['abs error tk0 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['tk1' '------------------------------------------']);
[~,hm,f]=check(tk1,tk1_jl);
hm.Title = ['abs error tk1 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['tk2' '------------------------------------------']);
[~,hm,f]=check(tk2,tk2_jl);
hm.Title = ['abs error tk2 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['DT' '------------------------------------------']);
[~,hm,f]=check(DT,DT_jl);
hm.Title = ['abs error DT step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['APHI' '------------------------------------------']);
[~,hm,f]=check(APHI,APHI_jl);
hm.Title = ['abs error APHI step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['vxf' '------------------------------------------']);
[~,hm,f]=check(vxf,vxf_jl);
hm.Title = ['abs error vxf step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['vyf' '------------------------------------------']);
[~,hm,f]=check(vyf,vyf_jl);
hm.Title = ['abs error vyf step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['pscale' '------------------------------------------']);
[~,~]=check(pscale,pscale_jl);
disp(['ETA' '------------------------------------------']);
[~,hm,f]=check(ETA,ETA_jl);
hm.Title = ['abs error ETA step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['ETAP' '------------------------------------------']);
[~,hm,f]=check(ETAP,ETAP_jl);
hm.Title = ['abs error ETAP step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['GGG' '------------------------------------------']);
[~,hm,f]=check(GGG,GGG_jl);
hm.Title = ['abs error GGG step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['GGGP' '------------------------------------------']);
[~,hm,f]=check(GGGP,GGGP_jl);
hm.Title = ['abs error GGGP step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['SXY0' '------------------------------------------']);
[~,hm,f]=check(SXY0,SXY0_jl);
hm.Title = ['abs error SXY0 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['SXX0' '------------------------------------------']);
[~,hm,f]=check(SXX0,SXX0_jl);
hm.Title = ['abs error SXX0 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RHOX' '------------------------------------------']);
[~,hm,f]=check(RHOX,RHOX_jl);
hm.Title = ['abs error RHOX step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RHOY' '------------------------------------------']);
[~,hm,f]=check(RHOY,RHOY_jl);
hm.Title = ['abs error RHOY step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RHOFX' '------------------------------------------']);
[~,hm,f]=check(RHOFX,RHOFX_jl);
hm.Title = ['abs error RHOFX step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RHOFY' '------------------------------------------']);
[~,hm,f]=check(RHOFY,RHOFY_jl);
hm.Title = ['abs error RHOFY step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RX' '------------------------------------------']);
[~,hm,f]=check(RX,RX_jl);
hm.Title = ['abs error RX step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['RY' '------------------------------------------']);
[~,hm,f]=check(RY,RY_jl);
hm.Title = ['abs error RY step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['ETAPHI' '------------------------------------------']);
[~,hm,f]=check(ETAPHI,ETAPHI_jl);
hm.Title = ['abs error ETAPHI step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['BETTAPHI' '------------------------------------------']);
[~,hm,f]=check(BETTAPHI,BETTAPHI_jl);
hm.Title = ['abs error BETTAPHI step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['PHI' '------------------------------------------']);
[~,hm,f]=check(PHI,PHI_jl);
hm.Title = ['abs error PHI step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['gx' '------------------------------------------']);
[~,hm,f]=check(gx,gx_jl);
hm.Title = ['abs error gx step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['gy' '------------------------------------------']);
[~,hm,f]=check(gy,gy_jl);
hm.Title = ['abs error gy step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['pr0' '------------------------------------------']);
[~,hm,f]=check(pr0,pr0_jl);
hm.Title = ['abs error pr0 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['pf0' '------------------------------------------']);
[~,hm,f]=check(pf0,pf0_jl);
hm.Title = ['abs error pf0 step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['vx' '------------------------------------------']);
[~,hm,f]=check(vx,vx_jl);
hm.Title = ['abs error vx step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['vy' '------------------------------------------']);
[~,hm,f]=check(vy,vy_jl);
hm.Title = ['abs error vy step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['qxD' '------------------------------------------']);
[~,hm,f]=check(qxD,qxD_jl);
hm.Title = ['abs error qxD step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['qyD' '------------------------------------------']);
[~,hm,f]=check(qyD,qyD_jl);
hm.Title = ['abs error qyD step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['pr' '------------------------------------------']);
[~,hm,f]=check(pr(2:end-1,2:end-1),pr_jl(2:end-1,2:end-1));
hm.Title = ['abs error pr step=' num2str(step)];
saveas(f, [hm.Title '.png']);
disp(['pf' '------------------------------------------']);
[~,hm,f]=check(pf(2:end-1,2:end-1),pf_jl(2:end-1,2:end-1));
hm.Title = ['abs error pf step=' num2str(step)];
saveas(f, [hm.Title '.png']);
end